//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public string ImageUrl { get; set; }
        public string Decription { get; set; }
        public int Cost { get; set; }
        public bool isActive { get; set; }
        public int CateID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> Wantity { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
